"""Reusable modal dialogs for the dashboard UI (project create, open, revision history)."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from .components import esc, help_term, label


def render_project_modals(
    labels: Mapping[str, str] | None = None,
    language_key: str = "generic",
    language_options: Sequence[Any] | None = None,
) -> str:
    """Renders the project wizard and research revision modal dialogs."""

    def L(key: str) -> str:
        return esc(label(labels, key))

    parts: list[str] = []

    # Modal: New Project (with Import & From-Scratch Tabs)
    parts.append('<dialog class="lixity-modal" id="modal-project-create" closedby="any" aria-labelledby="modal-create-title">')
    parts.append('  <div class="modal-card">')
    parts.append('    <div class="modal-header">')
    parts.append(f'      <h3 id="modal-create-title">{L("create_project")}</h3>')
    parts.append(f'      <button type="button" class="modal-close" data-close-modal aria-label="{L("modal_close")}">✕</button>')
    parts.append('    </div>')
    parts.append('    <div class="modal-tabs" role="tablist">')
    parts.append(f'      <button type="button" class="modal-tab-btn active" role="tab" id="tab-btn-import" aria-selected="true" data-tab-target="tab-pane-import">{L("wizard_import_tab")}</button>')
    parts.append(f'      <button type="button" class="modal-tab-btn" role="tab" id="tab-btn-scratch" aria-selected="false" data-tab-target="tab-pane-scratch">{L("wizard_scratch_tab")}</button>')
    parts.append('    </div>')

    # Tab Pane 1: Import existing manuscript
    parts.append('    <div class="modal-tab-pane active" id="tab-pane-import">')
    parts.append('      <form id="form-project-import" class="modal-body" method="dialog">')
    parts.append('        <input type="file" id="import-file-input" accept=".md,.markdown,.txt" hidden />')
    parts.append(f'        <button type="button" class="file-dropzone" id="import-dropzone" autofocus aria-label="{L("wizard_drop_aria")}">')
    parts.append('          <span class="dropzone-icon">')
    parts.append('            <svg width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="12" y1="18" x2="12" y2="12"></line><line x1="9" y1="15" x2="12" y2="12"></line><line x1="15" y1="15" x2="12" y2="12"></line></svg>')
    parts.append('          </span>')
    parts.append('          <span class="dropzone-text">')
    parts.append(f'            <strong>{L("wizard_drop_main")}</strong>')
    parts.append(f'            <span>{L("wizard_drop_sub")}</span>')
    parts.append('          </span>')
    parts.append('        </button>')
    parts.append('        <div class="file-preview-card" id="import-preview-box" style="display:none;">')
    parts.append('          <div class="fpc-header">')
    parts.append(f'            <span class="fpc-badge">{L("wizard_recognized")}</span>')
    parts.append('            <span class="fpc-filename" id="import-fpc-filename">manuscript.md</span>')
    parts.append('          </div>')
    parts.append('          <div class="fpc-meta">')
    parts.append(f'            <div class="fpc-stat"><span class="fpc-label">{L("wizard_scope")}</span> <strong id="import-fpc-stats"></strong></div>')
    parts.append(f'            <div class="fpc-stat"><span class="fpc-label">{L("wizard_analysis_language")}</span> <span id="import-fpc-lang"></span></div>')
    parts.append('          </div>')
    parts.append('        </div>')
    parts.append('        <div class="project-structure-hint">')
    parts.append(f'          <span>{help_term(labels, "import_manuscript", L("wizard_import_layout"))}</span>')
    parts.append('        </div>')
    parts.append('        <div class="form-group">')
    parts.append(f'          <label for="import-proj-title" class="form-label">{L("title")}</label>')
    parts.append(f'          <input class="ctl" id="import-proj-title" required placeholder="{L("wizard_import_title_hint")}" style="width:100%;"/>')
    parts.append('        </div>')
    parts.append('        <div class="form-row">')
    parts.append('          <div style="flex:1;">')
    parts.append(f'            <label for="import-proj-lang" class="form-label">{help_term(labels, "language", L("language"))}</label>')
    parts.append('            <select class="ctl" id="import-proj-lang" style="width:100%;">')
    for code, name in (("de", "Deutsch"), ("en", "English"), ("fr", "Français"), ("es", "Español"), ("it", "Italiano"), ("pt", "Português"), ("nl", "Nederlands")):
        sel = ' selected' if code == language_key else ''
        parts.append(f'              <option value="{code}"{sel}>{name}</option>')
    parts.append('            </select>')
    parts.append('          </div>')
    parts.append('          <div style="flex:2;">')
    parts.append(f'            <label for="import-proj-path" class="form-label">{L("wizard_project_folder")}</label>')
    parts.append(f'            <input class="ctl" id="import-proj-path" placeholder="{L("wizard_auto_folder")}" style="width:100%;"/>')
    parts.append(f'            <span class="ctl-note" style="display:block;margin-top:.25rem;font-size:.72rem;">{L("wizard_folder_note")}</span>')
    parts.append('          </div>')
    parts.append('        </div>')
    parts.append('        <div class="form-group">')
    parts.append(f'          <label class="form-checkbox"><input type="checkbox" id="import-proj-research"/> <span>{L("wizard_enable_research")}</span></label>')
    parts.append('        </div>')
    parts.append('        <p class="ctl-status project-form-status" id="import-project-status" role="alert" aria-live="assertive" hidden></p>')
    parts.append('        <div class="modal-footer">')
    parts.append(f'          <button type="button" class="ctl" data-close-modal>{L("modal_cancel")}</button>')
    parts.append(f'          <button type="submit" class="ctl primary" id="btn-submit-import-project" disabled>{L("wizard_import_action")}</button>')
    parts.append('        </div>')
    parts.append('      </form>')
    parts.append('    </div>')

    # Tab Pane 2: Start new project from scratch
    parts.append('    <div class="modal-tab-pane" id="tab-pane-scratch" style="display:none;">')
    parts.append('      <form id="form-project-create" class="modal-body" method="dialog">')
    parts.append('        <div class="project-structure-hint">')
    parts.append(f'          <span>{L("wizard_project_files")}</span>')
    parts.append('        </div>')
    parts.append('        <div class="form-group">')
    parts.append(f'          <label for="new-proj-title" class="form-label">{L("title")}</label>')
    parts.append(f'          <input class="ctl" id="new-proj-title" required placeholder="{L("wizard_title_example")}" style="width:100%;"/>')
    parts.append('        </div>')
    parts.append('        <div class="form-row">')
    parts.append('          <div style="flex:1;">')
    parts.append(f'            <label for="new-proj-lang" class="form-label">{help_term(labels, "language", L("language"))}</label>')
    parts.append('            <select class="ctl" id="new-proj-lang" style="width:100%;">')
    for code, name in (("de", "Deutsch"), ("en", "English"), ("fr", "Français"), ("es", "Español"), ("it", "Italiano"), ("pt", "Português"), ("nl", "Nederlands")):
        sel = ' selected' if code == language_key else ''
        parts.append(f'              <option value="{code}"{sel}>{name}</option>')
    parts.append('            </select>')
    parts.append('          </div>')
    parts.append('          <div style="flex:2;">')
    parts.append(f'            <label for="new-proj-path" class="form-label">{L("wizard_target_folder")}</label>')
    parts.append(f'            <input class="ctl" id="new-proj-path" placeholder="{L("wizard_subfolder")}" style="width:100%;"/>')
    parts.append(f'            <span class="ctl-note" style="display:block;margin-top:.25rem;font-size:.72rem;">{L("wizard_folder_note")}</span>')
    parts.append('          </div>')
    parts.append('        </div>')
    parts.append('        <div class="form-group">')
    parts.append(f'          <span class="form-label">{L("wizard_template_heading")}</span>')
    parts.append('          <div class="template-grid">')
    parts.append('            <label class="template-card active">')
    parts.append('              <input type="radio" name="proj_template" value="minimal" checked/>')
    parts.append(f'              <div class="tc-title">{L("wizard_minimal")}</div>')
    parts.append(f'              <div class="tc-desc">{L("wizard_minimal_desc")}</div>')
    parts.append('            </label>')
    parts.append('            <label class="template-card">')
    parts.append('              <input type="radio" name="proj_template" value="three_act"/>')
    parts.append(f'              <div class="tc-title">{L("wizard_three_act")}</div>')
    parts.append(f'              <div class="tc-desc">{L("wizard_three_act_desc")}</div>')
    parts.append('            </label>')
    parts.append('            <label class="template-card">')
    parts.append('              <input type="radio" name="proj_template" value="research"/>')
    parts.append(f'              <div class="tc-title">{L("wizard_research_template")}</div>')
    parts.append(f'              <div class="tc-desc">{L("wizard_research_template_desc")}</div>')
    parts.append('            </label>')
    parts.append('          </div>')
    parts.append('        </div>')
    parts.append('        <div class="form-group" style="margin-top:.4rem;">')
    parts.append(f'          <label class="form-checkbox"><input type="checkbox" id="new-proj-research"/> <span>{L("wizard_enable_research")}</span></label>')
    parts.append('        </div>')
    parts.append('        <p class="ctl-status project-form-status" id="new-project-status" role="alert" aria-live="assertive" hidden></p>')
    parts.append('        <div class="modal-footer">')
    parts.append(f'          <button type="button" class="ctl" data-close-modal>{L("modal_cancel")}</button>')
    parts.append(f'          <button type="submit" class="ctl primary" id="btn-submit-create-project">{L("create_project")}</button>')
    parts.append('        </div>')
    parts.append('      </form>')
    parts.append('    </div>')
    parts.append('  </div>')
    parts.append('</dialog>')

    # Modal: Open Project
    parts.append('<dialog class="lixity-modal" id="modal-project-open" closedby="any" aria-labelledby="modal-open-title">')
    parts.append('  <div class="modal-card">')
    parts.append('    <div class="modal-header">')
    parts.append(f'      <h3 id="modal-open-title">{help_term(labels, "open_existing", L("open_project"))}</h3>')
    parts.append(f'      <button type="button" class="modal-close" data-close-modal aria-label="{L("modal_close")}">✕</button>')
    parts.append('    </div>')
    parts.append('    <form id="form-project-open" class="modal-body" method="dialog">')
    parts.append('      <div class="form-group">')
    parts.append(f'        <label for="open-proj-path" class="form-label">{L("wizard_open_path")}</label>')
    parts.append('        <div class="project-path-row">')
    parts.append(f'          <input class="ctl" id="open-proj-path" required autofocus placeholder="{L("wizard_open_placeholder")}"/>')
    parts.append(f'          <button type="button" class="ctl" id="open-proj-choose" aria-controls="open-project-chooser" aria-expanded="false">{L("wizard_choose_action")}</button>')
    parts.append('        </div>')
    parts.append(f'        <p class="ctl-note">{L("wizard_open_note")}</p>')
    parts.append('      </div>')
    parts.append('      <div class="recent-projects-wrap" id="open-project-recent" style="display:none;margin-bottom:.75rem;">')
    parts.append(f'        <span class="ctl-label" style="font-size:.78rem;font-weight:600;margin-bottom:.3rem;display:block;">{L("recent_projects_heading")}</span>')
    parts.append('        <div class="recent-projects-chips" id="open-project-recent-list" style="display:flex;flex-wrap:wrap;gap:.4rem;"></div>')
    parts.append('      </div>')
    parts.append('      <div class="project-chooser" id="open-project-chooser" role="region" aria-labelledby="open-project-chooser-heading" hidden>')
    parts.append('        <div class="project-chooser-heading">')
    parts.append(f'          <strong id="open-project-chooser-heading">{L("wizard_choose_heading")}</strong>')
    parts.append(f'          <button type="button" class="ctl" id="open-project-chooser-close" aria-label="{L("modal_close")}">✕</button>')
    parts.append('        </div>')
    parts.append(f'        <p class="ctl-note">{L("wizard_choose_location")}</p>')
    parts.append(f'        <p class="ctl-note project-chooser-current">{L("wizard_choose_current")} <code id="open-project-chooser-path"></code></p>')
    parts.append('        <div class="project-chooser-toolbar">')
    parts.append(f'          <button type="button" class="ctl" id="open-project-chooser-home">{L("wizard_choose_home")}</button>')
    parts.append(f'          <button type="button" class="ctl" id="open-project-chooser-parent" disabled>{L("wizard_choose_parent")}</button>')
    parts.append(f'          <button type="button" class="ctl primary" id="open-project-chooser-select-folder" disabled>{L("wizard_choose_folder")}</button>')
    parts.append('        </div>')
    parts.append('        <p class="ctl-note" id="open-project-chooser-status" role="status" aria-live="polite"></p>')
    parts.append('        <ul class="project-chooser-list" id="open-project-chooser-list" aria-label="' + L("wizard_choose_entries") + '"></ul>')
    parts.append('      </div>')
    parts.append('      <div class="project-structure-hint" style="margin-top:.6rem;">')
    parts.append(f'        <span>{L("wizard_switch_prompt")} <button type="button" class="ctl-link" id="link-switch-to-import" style="background:none;border:none;color:var(--accent);text-decoration:underline;cursor:pointer;font-size:inherit;padding:0;">{L("wizard_switch_action")}</button></span>')
    parts.append('      </div>')
    parts.append('      <p class="ctl-status project-form-status" id="open-project-status" role="alert" aria-live="assertive" hidden></p>')
    parts.append('      <div class="modal-footer">')
    parts.append(f'        <button type="button" class="ctl" data-close-modal>{L("modal_cancel")}</button>')
    parts.append(f'        <button type="submit" class="ctl primary" id="btn-submit-open-project">{L("open")}</button>')
    parts.append('      </div>')
    parts.append('    </form>')
    parts.append('  </div>')
    parts.append('</dialog>')

    # One editor and history view for all authored research record kinds.
    parts.append('<dialog class="lixity-modal" id="modal-research-revision" closedby="any" aria-labelledby="research-revision-title">')
    parts.append('  <div class="modal-card">')
    parts.append('    <div class="modal-header">')
    parts.append(f'      <h3 id="research-revision-title">{L("research_revision_title")}</h3>')
    parts.append(f'      <button type="button" class="modal-close" data-close-modal aria-label="{L("modal_close")}">✕</button>')
    parts.append('    </div>')
    parts.append('    <div class="modal-tabs" role="tablist">')
    parts.append(f'      <button type="button" class="modal-tab-btn active" role="tab" id="research-revision-edit-tab" aria-controls="research-revision-form" aria-selected="true">{L("research_revision_edit")}</button>')
    parts.append(f'      <button type="button" class="modal-tab-btn" role="tab" id="research-revision-history-tab" aria-controls="research-revision-history" aria-selected="false">{L("research_revision_history")}</button>')
    parts.append('    </div>')
    parts.append('    <p class="ctl-note research-revision-meta" id="research-revision-kind"></p>')
    parts.append('    <div class="research-revision-updates" id="research-revision-source-updates" role="status" aria-live="polite" hidden></div>')
    parts.append('    <form id="research-revision-form" class="modal-body" method="dialog" role="tabpanel" aria-labelledby="research-revision-edit-tab" novalidate>')
    parts.append('      <section id="research-revision-merge" class="form-group" aria-labelledby="research-revision-merge-title" hidden>')
    parts.append(f'        <h4 id="research-revision-merge-title">{L("research_revision_merge_title")}</h4>')
    parts.append(f'        <p class="ctl-note">{L("research_revision_merge_help")}</p>')
    parts.append('        <div id="research-revision-merge-fields"></div>')
    parts.append(f'        <button type="button" class="ctl" id="research-revision-merge-apply">{L("research_revision_merge_apply")}</button>')
    parts.append('      </section>')
    parts.append('      <div id="research-revision-fields" class="research-revision-fields"></div>')
    parts.append('      <fieldset class="research-revision-choice">')
    parts.append(f'        <legend class="form-label">{L("research_revision_type")}</legend>')
    parts.append(f'        <label><input type="radio" name="research_revision_change_kind" value="correction" required/> <span><strong>{L("research_revision_correction")}</strong><small>{L("research_revision_correction_desc")}</small></span></label>')
    parts.append(f'        <label><input type="radio" name="research_revision_change_kind" value="supersession"/> <span><strong>{L("research_revision_supersession")}</strong><small>{L("research_revision_supersession_desc")}</small></span></label>')
    parts.append('      </fieldset>')
    parts.append(f'      <label for="research-revision-reason" class="form-label">{L("research_revision_reason")}</label>')
    parts.append('<textarea class="ctl" id="research-revision-reason" rows="2" maxlength="2000" required></textarea>')
    parts.append('      <details class="research-details" id="research-revision-citations-wrap" hidden>')
    parts.append(f'        <summary>{L("research_citations")}</summary>')
    parts.append('        <div class="research-details-body" id="research-revision-citations"></div>')
    parts.append('      </details>')
    parts.append('      <div class="modal-footer">')
    parts.append(f'        <button type="button" class="ctl" id="research-revision-reload" hidden>{L("research_revision_reload")}</button>')
    parts.append(f'        <button type="button" class="ctl" data-close-modal>{L("modal_cancel")}</button>')
    parts.append(f'        <button type="button" class="ctl" id="research-revision-batch-add">{L("research_revision_batch_add")}</button>')
    parts.append(f'        <button type="submit" class="ctl primary" id="research-revision-save">{L("research_revision_save")}</button>')
    parts.append('      </div>')
    parts.append('    </form>')
    parts.append('    <p class="ctl-status" id="research-revision-status" role="alert" aria-live="assertive" hidden></p>')
    parts.append('    <div id="research-revision-history" class="modal-body research-revision-history" role="tabpanel" aria-labelledby="research-revision-history-tab" hidden>')
    parts.append('      <ol id="research-revision-history-list" class="research-revision-history-list"></ol>')
    parts.append('      <div id="research-revision-history-detail"></div>')
    parts.append('    </div>')
    parts.append('  </div>')
    parts.append('</dialog>')

    parts.append('<dialog class="lixity-modal" id="modal-research-revision-batch" closedby="any" aria-labelledby="research-revision-batch-title">')
    parts.append('  <div class="modal-card">')
    parts.append('    <div class="modal-header">')
    parts.append(f'      <h3 id="research-revision-batch-title">{L("research_revision_batch_title")}</h3>')
    parts.append(f'      <button type="button" class="modal-close" data-close-modal aria-label="{L("modal_close")}">✕</button>')
    parts.append('    </div>')
    parts.append('    <div class="modal-body">')
    parts.append(f'      <p class="ctl-note">{L("research_revision_batch_help")}</p>')
    parts.append('      <ol id="research-revision-batch-list"></ol>')
    parts.append('      <p class="ctl-status" id="research-revision-batch-status" role="status" aria-live="polite" hidden></p>')
    parts.append('      <div class="modal-footer">')
    parts.append(f'        <button type="button" class="ctl" id="research-revision-batch-clear">{L("research_revision_batch_clear")}</button>')
    parts.append(f'        <button type="button" class="ctl" data-close-modal>{L("research_revision_batch_close")}</button>')
    parts.append(f'        <button type="button" class="ctl" id="research-revision-batch-check">{L("research_revision_batch_check")}</button>')
    parts.append(f'        <button type="button" class="ctl primary" id="research-revision-batch-apply" disabled>{L("research_revision_batch_apply")}</button>')
    parts.append('      </div>')
    parts.append('    </div>')
    parts.append('  </div>')
    parts.append('</dialog>')

    return "".join(parts)
