"""Reusable research manager panel (sources, search, dossiers, claims, decisions, grounding)."""

from __future__ import annotations

from collections.abc import Mapping

from .components import esc, help_term, label, loading_state


def render_research_panel(labels: Mapping[str, str] | None = None) -> str:
    """Renders the local research archive panel and its tab panes."""

    def L(key: str) -> str:
        return esc(label(labels, key))

    parts: list[str] = ['<section class="panel controls" id="research-manager">']
    parts.append(f"<h2>{L('research_panel')}</h2>")
    parts.append('<div class="row" style="align-items:center;justify-content:space-between;margin:0;">')
    parts.append(f'<p class="ctl-note" id="research-hint" style="margin:0;">{L("research_hint")}</p>')
    parts.append(f'<span class="ctl-status loading" id="r-active-root" style="font-weight:500;">{L("research_loading")}</span>')
    parts.append('</div>')

    parts.append(f'<button type="button" class="ctl" id="research-revision-batch-review" hidden>{L("research_revision_batch_review")}</button>')
    parts.append('<div class="row research-tabs" id="research-tabs" role="tablist">')
    parts.append(f'<button type="button" class="ctl active" data-rtab="sources" role="tab" aria-selected="true">{L("research_tab_sources")}</button>')
    parts.append(f'<button type="button" class="ctl" data-rtab="search" role="tab" aria-selected="false">{L("research_tab_search")}</button>')
    parts.append(f'<button type="button" class="ctl" data-rtab="dossiers" role="tab" aria-selected="false">{L("research_tab_dossiers")}</button>')
    parts.append(f'<button type="button" class="ctl" data-rtab="claims" role="tab" aria-selected="false">{L("research_tab_claims")}</button>')
    parts.append(f'<button type="button" class="ctl" data-rtab="decisions" role="tab" aria-selected="false">{L("research_tab_decisions")}</button>')
    parts.append(f'<button type="button" class="ctl" data-rtab="review" role="tab" aria-selected="false">{L("research_tab_review")}</button>')
    parts.append(f'<button type="button" class="ctl" data-rtab="grounding" role="tab" aria-selected="false">{L("research_tab_grounding")}</button>')
    parts.append('</div>')

    parts.append('<div id="research-init-box" class="ctl-group" style="display:none;">')
    parts.append(f'<span class="ctl-label">{help_term(labels, "research_init", L("research_not_initialized"))}</span>')
    parts.append(f'<p class="ctl-note">{L("research_init_note")}</p>')
    parts.append('<div class="row">')
    parts.append(f'<input class="ctl" id="r-init-title" placeholder="{L("research_project_title")}" style="min-width:200px;"/>')
    parts.append(f'<button class="ctl primary" id="r-init-btn">{L("research_init_action")}</button>')
    parts.append('</div>')
    parts.append('</div>')

    parts.append('<div class="research-tab-pane" id="rtab-sources">')
    parts.append('<div class="ctl-group" id="zotero-box">')
    parts.append('<h3>Zotero</h3>')
    parts.append(f'<p class="ctl-note">{L("zotero_intro")}</p>')
    parts.append('<div class="row">')
    parts.append(f'<label for="r-zotero-library">{L("zotero_library")}</label>')
    parts.append('<input class="ctl" id="r-zotero-library" value="users/0" placeholder="users/0" style="max-width:100%;"/>')
    parts.append(f'<button type="button" class="ctl" id="r-zotero-collections">{L("zotero_collections")}</button>')
    parts.append(f'<select class="ctl" id="r-zotero-collection" aria-label="{L("zotero_all")}" style="max-width:100%;"><option value="">{L("zotero_all")}</option></select>')
    parts.append('</div><div class="row">')
    parts.append(f'<input class="ctl" id="r-zotero-query" aria-label="{L("research_search_query")}" placeholder="{L("research_search_query")}" style="flex:1;min-width:0;"/>')
    parts.append(f'<button type="button" class="ctl primary" id="r-zotero-browse">{L("zotero_browse")}</button>')
    parts.append('</div>')
    parts.append(f'<label><input type="checkbox" id="r-zotero-retention"/> {L("research_retention")}</label>')
    parts.append('<div id="r-zotero-results" aria-live="polite"></div></div>')
    parts.append('<div id="r-local-import">')

    parts.append('<div class="ctl-group">')
    parts.append(f'<span class="ctl-label">{help_term(labels, "research_ingest", L("research_ingest_heading"))}</span>')
    parts.append('<div class="row" style="margin-bottom:.5rem;">')
    parts.append('<input class="ctl" type="file" id="r-ingest-file" accept=".txt,.md,.text,.pdf"/>')
    parts.append(f'<input class="ctl" id="r-ingest-title" placeholder="{L("research_source_title")}" style="min-width:180px;"/>')
    parts.append(f'<input class="ctl" id="r-ingest-tags" placeholder="{L("research_tags_example")}" style="min-width:180px;"/>')
    parts.append('</div>')
    parts.append(f'<label for="r-ingest-origin-url">{L("ctx_origin_url")}</label>')
    parts.append('<input class="ctl" type="url" id="r-ingest-origin-url" maxlength="2000" aria-describedby="r-ingest-origin-help" placeholder="https://example.org/source" style="width:100%;margin:.3rem 0;"/>')
    parts.append(f'<p class="ctl-note" id="r-ingest-origin-help">{L("research_origin_url_help")}</p>')
    parts.append('<div class="row" id="r-ocr-diagnostic-box" style="margin-bottom:.5rem;display:none;"></div>')
    parts.append('<div class="row" style="margin-bottom:.5rem;">')
    parts.append(f'<textarea class="ctl" id="r-ingest-text" placeholder="{L("research_source_text")}" rows="3" style="width:100%;font-family:inherit;"></textarea>')
    parts.append('</div>')
    parts.append('<div class="row" style="align-items:center;">')
    parts.append(f'<label style="display:flex;align-items:center;gap:.3rem;font-size:.85rem;cursor:pointer;"><input type="checkbox" id="r-ingest-retention" data-help="{L("help_research_ingest")}"/> <span>{L("research_retention")}</span></label>')
    parts.append(f'<button class="ctl primary" id="r-ingest-btn">{L("research_ingest_action")}</button>')
    parts.append('</div>')
    parts.append('</div>')
    parts.append('</div>')
    parts.append(f'<h3>{L("zotero_retained")}</h3>')
    parts.append(f'<input class="ctl" type="search" id="r-filter-sources" aria-label="{L("research_filter_sources")}" placeholder="{L("research_filter_sources")}" style="width:100%;margin-bottom:.5rem;"/>')
    parts.append('<p class="ctl-note" id="r-filter-sources-status" aria-live="polite" hidden></p>')
    parts.append(f'<div id="research-sources-list">{loading_state(label(labels, "research_loading"))}</div>')
    parts.append('</div>')

    parts.append('<div class="research-tab-pane" id="rtab-search" style="display:none;">')
    parts.append('<div class="ctl-group">')
    parts.append(f'<span class="ctl-label">{help_term(labels, "research_search", L("research_search_heading"))}</span>')
    parts.append('<div class="row">')
    parts.append(f'<input class="ctl" id="r-search-query" placeholder="{L("research_search_query")}" style="min-width:240px;flex:1;"/>')
    parts.append(f'<select class="ctl" id="r-search-scope" aria-label="{L("research_search_scope")}">')
    for scope, scope_label in (("all", "research_search_all"), ("sources", "research_tab_sources"),
                         ("dossiers", "research_tab_dossiers"), ("claims", "research_tab_claims"),
                         ("decisions", "research_tab_decisions")):
        parts.append(f'<option value="{scope}">{L(scope_label)}</option>')
    parts.append('</select>')
    parts.append(f'<button class="ctl primary" id="r-search-btn">{L("research_search_action")}</button>')
    parts.append('</div>')
    parts.append('</div>')
    parts.append('<div id="research-search-results"></div>')
    parts.append('</div>')

    parts.append('<div class="research-tab-pane" id="rtab-dossiers" style="display:none;">')
    parts.append('<div class="ctl-group">')
    parts.append(f'<span class="ctl-label">{help_term(labels, "research_dossier", L("research_dossier_heading"))}</span>')
    parts.append('<div class="row" style="margin-bottom:.5rem;">')
    parts.append(f'<input class="ctl" id="r-dos-title" placeholder="{L("research_dossier_title")}" style="min-width:220px;"/>')
    parts.append(f'<input class="ctl" id="r-dos-tags" placeholder="{L("research_tags")}" style="min-width:180px;"/>')
    parts.append(f'<input class="ctl" id="r-dos-eids" aria-label="{L("research_evidence_ids")}" data-help="{L("help_research_passage")}" placeholder="{L("research_evidence_ids")}" style="flex:1;min-width:200px;"/>')
    parts.append('</div>')
    parts.append('<div class="row" style="margin-bottom:.5rem;">')
    parts.append(f'<textarea class="ctl" id="r-dos-body" placeholder="{L("research_dossier_body")}" rows="4" style="width:100%;font-family:inherit;"></textarea>')
    parts.append('</div>')
    parts.append('<div class="row">')
    parts.append(f'<button class="ctl primary" id="r-dos-create-btn">{L("research_dossier_action")}</button>')
    parts.append('</div>')
    parts.append('</div>')
    parts.append(f'<input class="ctl" type="search" id="r-filter-dossiers" aria-label="{L("research_filter_dossiers")}" placeholder="{L("research_filter_dossiers")}" style="width:100%;margin-bottom:.5rem;"/>')
    parts.append('<p class="ctl-note" id="r-filter-dossiers-status" aria-live="polite" hidden></p>')
    parts.append(f'<div id="research-dossiers-list">{loading_state(label(labels, "research_loading"))}</div>')
    parts.append('</div>')

    # Tab Pane: Claims & Evidence Links
    parts.append('<div class="research-tab-pane" id="rtab-claims" style="display:none;">')
    parts.append('  <div class="ctl-group">')
    parts.append(f'    <span class="ctl-label">{help_term(labels, "research_claim", L("research_claim_heading"))}</span>')
    parts.append('    <div class="row" style="margin-bottom:.5rem;">')
    parts.append(f'      <input class="ctl" id="r-claim-title" placeholder="{L("research_claim_title")}" style="min-width:220px;flex:1;"/>')
    parts.append(f'      <select class="ctl" id="r-claim-confidence" aria-label="{L("research_confidence_field")}" data-help="{L("help_research_confidence")}" style="min-width:140px;">')
    parts.append(f'        <option value="hypothetical">{L("research_confidence_hypothetical")}</option>')
    parts.append(f'        <option value="evidenced">{L("research_confidence_evidenced")}</option>')
    parts.append(f'        <option value="disputed">{L("research_confidence_disputed")}</option>')
    parts.append('      </select>')
    parts.append(f'      <input class="ctl" id="r-claim-tags" placeholder="{L("research_tags")}" style="min-width:160px;"/>')
    parts.append(f'      <select class="ctl" id="r-claim-dossier-select" aria-label="{L("research_dossier")}" style="min-width:180px;"><option value="">{L("research_no_dossier")}</option></select>')
    parts.append('    </div>')
    parts.append('    <div class="row" style="margin-bottom:.5rem;">')
    parts.append(f'      <textarea class="ctl" id="r-claim-statement" placeholder="{L("research_claim_statement")}" rows="3" style="width:100%;font-family:inherit;"></textarea>')
    parts.append('    </div>')
    parts.append('    <div class="row" style="margin-bottom:.5rem;">')
    parts.append(f'      <input class="ctl" id="r-claim-time" placeholder="{L("research_claim_time")}" style="flex:1;min-width:150px;"/>')
    parts.append(f'      <input class="ctl" id="r-claim-place" placeholder="{L("research_claim_place")}" style="flex:1;min-width:150px;"/>')
    parts.append(f'      <input class="ctl" id="r-claim-actors" placeholder="{L("research_claim_actors")}" style="flex:1.5;min-width:180px;"/>')
    parts.append('    </div>')
    parts.append('    <div class="row">')
    parts.append(f'      <button class="ctl primary" id="r-claim-create-btn">{L("research_claim_action")}</button>')
    parts.append('      <button type="button" class="ctl secondary" id="r-claim-matrix-btn" style="margin-left:.5rem;">Export Claim Matrix</button>')
    parts.append('    </div>')
    parts.append('  </div>')
    parts.append('  <div class="ctl-group" style="margin-top:.8rem;">')
    parts.append(f'    <span class="ctl-label">{help_term(labels, "research_evidence", L("research_link_heading"))}</span>')
    parts.append('    <div class="row" style="margin-bottom:.5rem;">')
    parts.append(f'      <select class="ctl" id="r-link-claim-select" aria-label="{L("research_select_claim")}" style="min-width:220px;flex:1;"><option value="">{L("research_select_claim")}</option></select>')
    parts.append(f'      <input class="ctl" id="r-link-passage-id" aria-label="{L("research_passage_id")}" data-help="{L("help_research_passage")}" placeholder="{L("research_passage_id")}" style="min-width:220px;flex:1;font-family:monospace;"/>')
    parts.append(f'      <select class="ctl" id="r-link-relation" aria-label="{L("research_relation_field")}" data-help="{L("help_research_relation")}" style="min-width:140px;">')
    parts.append(f'        <option value="supports">{L("research_relation_supports")}</option>')
    parts.append(f'        <option value="contradicts">{L("research_relation_contradicts")}</option>')
    parts.append(f'        <option value="qualifies">{L("research_relation_qualifies")}</option>')
    parts.append(f'        <option value="contextualizes">{L("research_relation_contextualizes")}</option>')
    parts.append('      </select>')
    parts.append('    </div>')
    parts.append('    <div class="row" style="margin-bottom:.5rem;">')
    parts.append(f'      <input class="ctl" id="r-link-rationale" placeholder="{L("research_link_rationale")}" style="flex:1;"/>')
    parts.append(f'      <button class="ctl primary" id="r-link-evidence-btn">{L("research_link_action")}</button>')
    parts.append('    </div>')
    parts.append('  </div>')
    parts.append(f'  <div id="research-claims-list">{loading_state(label(labels, "research_loading"))}</div>')
    parts.append('</div>')

    # Tab Pane: Decisions
    parts.append('<div class="research-tab-pane" id="rtab-decisions" style="display:none;">')
    parts.append('  <div class="ctl-group">')
    parts.append(f'    <span class="ctl-label">{help_term(labels, "research_decision", L("research_decision_heading"))}</span>')
    parts.append('    <div class="row" style="margin-bottom:.5rem;">')
    parts.append(f'      <input class="ctl" id="r-decision-title" placeholder="{L("research_decision_title")}" style="min-width:220px;flex:1;"/>')
    parts.append(f'      <select class="ctl" id="r-decision-claim-select" aria-label="{L("research_select_claim")}" style="min-width:220px;flex:1;"><option value="">{L("research_no_claim_linked")}</option></select>')
    parts.append('    </div>')
    parts.append('    <div class="row" style="margin-bottom:.5rem;">')
    parts.append(f'      <textarea class="ctl" id="r-decision-rationale" placeholder="{L("research_decision_rationale")}" rows="3" style="width:100%;font-family:inherit;"></textarea>')
    parts.append('    </div>')
    parts.append('    <div class="row" style="margin-bottom:.5rem;">')
    parts.append(f'      <input class="ctl" id="r-decision-plot" placeholder="{L("research_decision_plot")}" style="flex:1;min-width:250px;"/>')
    parts.append('    </div>')
    parts.append('    <div class="row" style="align-items:center;justify-content:space-between;">')
    parts.append('      <label style="display:flex;align-items:center;gap:.35rem;font-size:.85rem;cursor:pointer;">')
    parts.append('        <input type="checkbox" id="r-decision-deviation"/>')
    parts.append(f'        <span>{help_term(labels, "research_deviation", L("research_deviation_checkbox"))}</span>')
    parts.append('      </label>')
    parts.append(f'      <button class="ctl primary" id="r-decision-create-btn">{L("research_decision_action")}</button>')
    parts.append('    </div>')
    parts.append('  </div>')
    parts.append(f'  <div id="research-decisions-list">{loading_state(label(labels, "research_loading"))}</div>')
    parts.append('</div>')

    parts.append('<div class="research-tab-pane" id="rtab-review" style="display:none;">')
    parts.append(f'<h3>{L("research_editorial_heading")}</h3>')
    parts.append(f'<p class="ctl-note">{L("research_editorial_help")}</p>')
    parts.append(f'<button type="button" class="ctl" id="r-review-refresh">{L("research_editorial_refresh")}</button>')
    parts.append('<div id="research-editorial-review" aria-live="polite"></div>')
    parts.append('</div>')

    parts.append('<div class="research-tab-pane" id="rtab-grounding" style="display:none;">')
    parts.append('<div class="ctl-group">')
    parts.append(f'<span class="ctl-label">{help_term(labels, "research_comparison", L("research_ground_heading"))}</span>')
    parts.append('<div class="row">')
    parts.append(f'<select class="ctl" id="r-ground-source-select" aria-label="{L("research_select_source")}" style="min-width:220px;"><option value="">{L("research_select_source")}</option></select>')
    parts.append(f'<button class="ctl primary" id="r-ground-btn">{L("research_ground_action")}</button>')
    parts.append('</div>')
    parts.append('</div>')
    parts.append('<div id="research-grounding-results"></div>')
    parts.append('</div>')

    parts.append('<div class="ctl-status" id="research-status-bar" role="status" aria-live="polite"></div>')
    parts.append("</section>")

    return "".join(parts)
